### PR TITLE
Fix Tentative for Issue 164

### PR DESCRIPTION
**Pull request by gw4e**
Here a tentative fox for issue 164.

### CODE REVIEW

**Comment by KristianKarl** [comment]
Looks good so far!

However, I would like this PR also to be able to write the edge dependency property to a graphml file.
That should be done in `org.graphwalker.io.factory.yed.YEdContextFactory#getAsString`

Also, I would like to see tests where a graphml file is read and written, and the dependency property is asserted. Those read and write tests should be in here: https://github.com/GraphWalker/graphwalker-project/blob/master/graphwalker-io/src/test/java/org/graphwalker/io/factory/yed/YEdContextFactoryTest.java

**Comment by gw4e** [comment]
Can you enlight me why the codecov failed ? I dont get it ...

**Comment by KristianKarl** [comment]
Generally it could happen when code (statements) are added, and test coverage is more or less the same, the difference in percentage then can decline. But when it's so little as in this case, you should not be concerned.

But it's always good practice and have a look at the code coverage links. Did you have a look at them?

**Comment by nilols** [comment]
I think we talked about configure codecov a bit in another PR because it's to picky or codecov just hates me...

**Comment by gw4e** [comment]
Well, I tried to add some new tests to augment the coverage. My understanding is that the coverage threshold seems very sensitive to small variation.

**Comment by nilols** [comment]
indeed

**Comment by KristianKarl** [comment]
:+1: from me. You wanna have a look @nilols ?

**Comment by nilols** [comment]
LGTM 👍

**Pull request merged**
