### PR TITLE
Enable multiple graphml

### PR DESCRIPTION
**Pull request by neofreko**
This small patch will enable loading multiple graphml files thus we can use and run shared models.

### CODE REVIEW

**Comment by toredal** [comment]
Thanks for the contribution!

When I test it, I can't load multiple graphml. However, if I have loaded 1 graphml model, then loading multiple graphml files works.

**This is what I did:**
1 - Build PR and start studio, and open browser **localhost:9090**
2 - Click on **Load test**
3 - Select multiple graphml files

**What I expected:**
All models loaded in seperate tabs

**What actually happened:**
No model was opened.

**Comment by neofreko** [comment]
@toredal 
Thanks for reviewing. I'll share my graphml files here tomorrow so you can this PR with it.

**Comment by toredal** [comment]
@neofreko Yeah, `graphml` files was my understanding.
FYI, I used the graphml files from: https://github.com/GraphWalker/graphwalker-project/tree/master/graphwalker-cli/src/test/resources/graphml/shared_state

**Comment by neofreko** [comment]
@toredal 
I tried the models from `shared_state` example above. It didn't load for the first time, then it loads for any subsequent retries.
I tried in incognito window as well. It loads in the first attempt.

GraphWalker Studio 2019-05-15 10-50-23

Could it be something to do with the websocket part? I'll try to reproduce it again later.

**Comment by nilols** [comment]
@neofreko @KristianKarl This one is kind of old, should we close this one?

**Comment by neofreko** [comment]
@nilols I'm fine with that.

**Pull request closed without merging**
