### PR TITLE
Bug fix for statistcs

### PR DESCRIPTION
**Pull request by KristianKarl**

### CODE REVIEW

**Comment by KristianKarl** [comment]
@nilols The getResults from the Result class in graphwalker-java returns a JSONObject with all results. This has it's pros and cons. 
- The pros are that is can be used in a flexible way in many places that need results as string, but in a structured way. 
- The con is that its not strongly typed. There is an obvious risk of run type errors for querying the wrong individual test result. But, I would rather use the Profiler class instead for getting that typed result data instead.

Do we have more fixes we want to add to 3.4.1?

**Comment by KristianKarl** [comment]
I noticed that pulling the results does not work for the maven-plugin.
I'm working on a fix.

**Comment by nilols** [comment]
Not sure the best is to expose the result directly as json object, I think I would prefer that user facing libraries handle the json serialization so that core is as simple as possible (POJO)

**Comment by KristianKarl** [comment]
I need to re-work this one. 
I want to add unit tests, and a fix for #65

**Pull request closed without merging**
