### PR TITLE
Update the studio module

### PR DESCRIPTION
**Pull request by nilols**
Use webpack to build a bundle from the studio source, also include jshint to check the source for lint errors

### CODE REVIEW

**Comment by KristianKarl** [comment]
Is there a special way to build this, or does `mvn package -pl graphwalker-studio -am` work

**Comment by nilols** [comment]
it should work due to that the generated bundle is also in the repo

**Comment by KristianKarl** [comment]
+1

**Comment by KristianKarl** [comment]
:+1:

**Pull request merged**
