### PR TITLE
Fix for missing implementation for BLOCKED feature

### PR DESCRIPTION
**Pull request by KristianKarl**
Fix for issue #144

### CODE REVIEW

**Comment by KristianKarl** [comment]
The feature BLOCKED can be enabled or disabled(default).

I updated the PR, by moving the -b option from global to individual command.
So, an example of enabling the BLOCKED feature would be:
`offline -b -g json/graphWithBlockedElements.json`

**Comment by KristianKarl** [comment]
Good point Chabane! 
I updated the PR, so that the BLOCKED feature now is the default.

If a user wants to disable it, the following command line shows how:
`offline -b false -g json/graphWithBlockedElements.json`

@gw4e ^

**Comment by gw4e** [comment]
Will now focus on testing.

**Comment by gw4e** [comment]
Hi

I did  not get enough time to test.
I was expecting to do them on thursday.
Sorry for that .

Regards

**Comment by KristianKarl** [comment]
Oh, my bad. 
I thought you where going back to you regular testing :-)

But if you do find something, please let me know.

Best Kristian

**Pull request merged**
