### PR TITLE
Copy properties when a new model is created from a RuntimeModel

### PR DESCRIPTION
**Pull request by nilols**

### CODE REVIEW

**Comment by nilols** [comment]
fixes https://github.com/GraphWalker/graphwalker-project/issues/180

**Comment by KristianKarl** [comment]
@nilols I think the list of requirements should be copied as well, don't you think?

**Comment by KristianKarl** [comment]
:+1:

**Comment by gw4e** [comment]
Sounds good !

**Comment by KristianKarl** [comment]
:+1:

**Pull request merged**
