### PR TITLE
Handle and generate multiple source files for multimodel json file

### PR DESCRIPTION
**Pull request by KristianKarl**

### CODE REVIEW

**Comment by KristianKarl** [comment]
@nilols  I have added the capability to generate individual interface source files from a single json model file, that contain multiple models. Such as  [PetClinic.json](https://github.com/GraphWalker/graphwalker-project/blob/7374b58527ad5850f794cbb98386f9b25479d8f6/graphwalker-studio/src/test/resources/json/PetClinic.json)

Could you review it? I don't think that I messed up to badly.

**Comment by KristianKarl** [comment]
I'll need to fix the Windows incompatible test first

**Comment by nilols** [comment]
@KristianKarl sorry, been on vacation. I was thinking a bit on the SourceFile, several of the constructors will generate strange output files e.g. if input path would be `/model.graphml` the output path would be `/.java` instead of `/model.java`, the solution could be to remove some of the constructors due to that they are not all used (what I could see)

**Comment by KristianKarl** [comment]
@nilols Np agreed.

**Pull request merged**
