### PR TITLE
Fix for issue #114

### PR DESCRIPTION
**Pull request by nbdnnm**
@KristianKarl have a look on this fix please, does it impact something
This solution has a side effect, when I put a list of more that 2 stop conditions and the last one was already reached, GW still think that it should be reached and continue to generate a path

image

but it is some another issue I think
or maybe you know some gw restrictions which doesn't allow to have more that 2 conditions

[googleTranslator.zip](https://github.com/GraphWalker/graphwalker-project/files/629389/googleTranslator.zip)

### CODE REVIEW

**Comment by KristianKarl** [comment]
Good catch! 
I'll start looking at this today.
We should have a unit test for this...

**Comment by nbdnnm** [comment]
I think I am not able to write a unit tests
I don't understand GW on unit level I am not experienced in unit testing at all

**Comment by KristianKarl** [comment]
I did some digging into this, and the problem seems a bit bigger than I initially thought.
The logical AND'ing and OR'ing of more than 2 stop conditions seems not to work very well.
I need to have a closer look.

**Comment by nilols** [comment]
I had to rewrite the git history so this PR is way to big, could you please update your fork and create a new PR, sorry for the trouble =(

**Pull request closed without merging**
