### PR TITLE
Suggested fix for issue 193

### PR DESCRIPTION
**Pull request by KristianKarl**

### CODE REVIEW

**Comment by KristianKarl** [comment]
@nilols This is suggested fix. It uses the given context(s), and a given start element to reset the machine.

**Comment by nilols** [comment]
fixes https://github.com/GraphWalker/graphwalker-project/issues/193

**Comment by nilols** [comment]
The failed build seems to be a glitch on travis, but I'm thinking that there might exist a solution to this without the need to change the core module.

**Comment by nilols** [comment]
I played around with the test example that you had @KristianKarl in the issue #193, and by doing this
```java
    context.setNextElement(machine.getProfiler().getExecutionPath().get(0).getElement());
    context.setExecutionStatus(ExecutionStatus.NOT_EXECUTED);
    machine = new SimpleMachine(context);
```
you could reset the execution and restart, doing this in the REST module would probably be something like this, haven't tried it yet but if it works you only need to change in the rest module 
```java
  public String restart() {
    logger.debug("Received restart");
    JSONObject resultJson = new JSONObject();
    try {
      Execution execution = machine.getProfiler().getExecutionPath().get(0);
      contexts = contexts.stream().peek(context -> {
        if (execution.getContext().equals(context)) {
          context.setNextElement(execution.getElement());
        }
        context.setExecutionStatus(ExecutionStatus.NOT_EXECUTED);
      }).collect(Collectors.toList());
      machine = new SimpleMachine(contexts);
      resultJson.put("result", "ok");
    } catch (Exception e) {
      e.printStackTrace();
      resultJson.put("result", "nok");
      resultJson.put("error", e.getMessage());
    }
    return resultJson.toString();
  }
```

**Comment by KristianKarl** [comment]
@nilols  I like your solution much better. Less invasive.
I pushed your changes into this PR

**Pull request merged**
